env:
  matrix:
    - RUST_VERSION=1.11.0
    - RUST_VERSION=1.12.0

addons:
  apt:
    packages:
      - realpath
      - coreutils

script:
  - pip install --user awscli --ignore-installed six
  - export PATH=$PATH:$HOME/.local/bin
  - ./travis.sh
